\c fruitier_dev;

INSERT INTO fruitier ( name, Taste, Color, Nutrition, Origin, Season, Picture) VALUES
('Ackee', 'mild nutty flavor', 'bright red to orange exterior and yellow interior', 'healthy fats, vitamins, and minerals', 'Caribbean', 'All year-round'),
('Soursop', 'sweet and tangy', 'green exterior, white interior', 'rich in vitamin C, fiber, and antioxidants', 'Caribbean', 'All year-round'),
('Mango', 'sweet and juicy flesh', ' red, green, yellow, and orange', 'rich in vitamins A and C, as well as dietary fiber', 'late spring and summer months', 'various coontry', 'https://www.dreamstime.com/stock-image-mango-ripe-white-background-image35283521'),
('Papaya', 'sweet & tropical flavor', 'ripe orange unripe green', 'high in vitamin C, A, and folate', 'Caribbean', 'All year-around'),
('Pineapple', 'sweet and tangy flavor', 'rough brown exterior and yellow inside', 'Rich in vitamin C, manganese, and antioxidants', 'spring and summer', 'Caribbean'),
('Baobab', 'Tart and citrusy', 'Brown or green', 'High in vitamin C and antioxidants', 'year-round', 'Africa'),
('Marula', 'Sweet and tart', 'Yellow or green', 'Rich in vitamin C and antioxidants', 'late spring to early summer', 'Africa'),
('Guava', 'Sweet and fragrant', 'Green or pink.', 'igh in vitamin C and dietary fiber', 'Variable, often available year-round', 'Africa'),
('Durian', 'sweet and savory', 'Spiky outer shell and custard flesh', 'Rich in energy, vitamin C, and potassium', 'Variable, often available in summer', 'Asia'),
('Lychee', 'Sweet and floral', 'Reddish-pink outside and translucent white flesh', 'High in vitamin C, vitamin B6, niacin, riboflavin, folate, copper, potassium,', ' B6, niacin, riboflavin, folate, copper, potassium', 'Asia'),
('Dragon Fruit', 'Dragon Fruit', 'pink or yellow skin with white or red flesh', 'Rich in vitamin C, fiber, antioxidants, and several essential minerals', 'All year-round', 'Asia'),
('Apple', 'Sweet to tart', 'Various, red, green, and yellow', 'High in fiber and vitamin C', 'Late summer to fall', 'Europe'),
('Cherry', 'Sweet or tart', 'Red, yellow, or dark purple', 'High in antioxidants, vitamin C, and potassium.', 'Late spring to early summer', 'Europe'),
('Grapes', 'Sweet or tart', 'Green, red, or purple', 'High in antioxidants, vitamins, and minerals', 'Late summer to early fall', 'Europe'),
('Blueberry', 'Sweet and tart', 'Blue or purple', 'High in antioxidants, vitamin C, and fiber', 'Late spring to early fall', 'N America'),
('Cranberry', 'Tart', 'Red', 'High in vitamin C and antioxidants', 'Late fall.', 'N America'),
('Avocado', 'Creamy and nutty', 'Green.', 'High in healthy fats, potassium, and vitamins', ' Variable, All year-round', 'N America'),
('Pineapple', 'Brown, fuzzy skin with green flesh ', 'Brown on the outside, yellow inside', 'High in vitamin C and manganese', ' Year-round', 'Oceania'),
('Passion Fruit', 'angy and sweet', 'Purple or yellow skin ', 'High in fiber, vitamins, and antioxidants', 'Variable, All year-round', 'Oceania'),
('Kiwifruit', 'Sweet and slightly tart.', 'Brown, fuzzy skin with green flesh','High in vitamin C, vitamin K, and dietary fiber', 'Late fall to early spring', 'Oceania'),
('Açaí Berry ', 'Earthy and mildly sweet', 'Dark purple', 'High in antioxidants, healthy fats, and fiber', 'All Year-round.', 'S America'),
('Papaya ', 'Sweet and tropical', 'Green when unripe, orange when ripe.', 'High in vitamin C, vitamin A, and folate', ' Year-round', 'S America'),
('Mango ', 'Sweet and juicy', 'Various, red, green, yellow, and orange', 'High in vitamins A and C, and dietary fiber', 'Late spring to summer.', 'S America')
